### ISSUE TITLE
If there are no regions, dataset table does not show empty state

### ISSUE THREAD

**Issue by Mittmich** [gerlichlab/hicognition#15]
If there are no regions in the database, the dataset table component just shows the spinner forever
![table_spinner](https://user-images.githubusercontent.com/29502987/154988905-f1ccc5e6-2b9f-43b0-a91b-5d4ef98b3c9d.png)

**Comment by cchlanger** [comment]
Last spinner bug should be fixed in: 
3298592cd1ffc88a68fd328dc56b11e0b88958de
