### ISSUE TITLE
Processing stuck

### ISSUE THREAD

**Issue by FedeTelo** [gerlichlab/hicognition#28]
I have been trying the new HiCognition version (@206) and since I have created my account I have two datasets in download that seem to be stuck and preventing any further processing of other data (see image below, this is has been ongoing since last week).

![image](https://github.com/gerlichlab/hicognition/assets/57997363/603c4e31-cf2f-46c5-9420-6af70e62e820)

**Comment by cchlanger** [comment]
This was independent of the HiCognition software, the machine ran out of disc space. The data directory was switched onto a bigger partition.
